const defaultInputs = {
  casaCentral: [
    {
      name: "nombrePropietario",
      label: "Nombre Propietario*",
      type: "text",
      placeholder: "Buscar",
      minWidth: "l",
      field: "nombre",
    },
    {
      name: "cuil",
      label: "CUIT/CUIL*",
      type: "number",
      placeholder: "",
      minWidth: "m",
      field: "cuil",
    },
    {
      name: "fechaCambioDomicilio",
      label: "Fecha de cambio de domicilio*",
      type: "date",
      placeholder: "Carga automática",
      field: "fecha_cambio_domicilio",
    },
  ],
  datosDomicilio: [
    {
      name: "ocupante",
      label: "Ocupante",
      type: "text",
      field: "ocupante",
    },
    {
      name: "codigoPostal",
      label: "Cod. Postal",
      type: "text",
      field: "cod_postal",
    },
    {
      name: "calle",
      label: "Calle*",
      type: "text",
      placeholder: "Buscar",
      minWidth: "m",
      field: "nom_calle_dom_esp",
    },
    {
      name: "nroDomicilio",
      label: "Nro. de Domicilio",
      type: "number",
      placeholder: "",
      field: "nro_dom_esp",
    },
    {
      name: "piso",
      label: "Piso",
      type: "number",
      placeholder: "",
      field: "nro_dom_esp",
    },
    {
      name: "manzana",
      label: "Manzana",
      type: "number",
      placeholder: "",
      field: "manzana",
    },
    {
      name: "parcela",
      label: "Parcela",
      type: "number",
      placeholder: "",
      field: "parcela",
    },
    {
      name: "barrio",
      label: "Barrio",
      type: "text",
      placeholder: "",
      minWidth: "m",
      field: "nom_barrio_dom_esp",
    },
    {
      name: "ciudad",
      label: "Ciudad",
      type: "text",
      placeholder: "",
      field: "ciudad_dom_esp",
    },
    {
      name: "superficieLote",
      label: "Superficie Lote",
      type: "number",
      placeholder: "",
      field: "superficie",
    },
    {
      name: "superficieEdificada",
      label: "Superficie Edificada",
      type: "number",
      placeholder: "",
      field: "superficie_edificada",
    },
    {
      name: "situacionInmueble",
      label: "Situación",
      type: "text",
      minWidth: "m",
      placeholder: "",
      fields: [
        { fieldName: "baldio_country", frontName: "Baldío" },
        { fieldName: "baldio_sucio", frontName: "Baldío Sucio" },
        { fieldName: "construccion", frontName: "Construcción" },
        { fieldName: "edificado", frontName: "Edificado" },
        { fieldName: "exhimido", frontName: "Exhimido" },
        { fieldName: "jubilado", frontName: "Jubilado" },
        { fieldName: "parquizado", frontName: "Parquizado" },
        { fieldName: "union_tributaria", frontName: "Union Tributaria" },
        { fieldName: "debito_automatico", frontName: "Debito Automatico" },
      ],
    },
  ],
  datosLiquidacion: [
    {
      name: "saldoTotal",
      label: "Saldo Total Adeudado",
      type: "number",
      placeholder: "Seleccionar",
      minWidth: "m",
      field: "saldo_adeudado",
    },
    {
      name: "ultimoPeriodo",
      label: "Último periodo de liquidación",
      type: "text",
      placeholder: "yyyy/mm",
      minWidth: "m",
      field: "ultimo_periodo",
    },
    {
      name: "entregaCedulon",
      label: "Entrega Cedulón",
      type: "checkbox",
      placeholder: "",
      field: "emite_cedulon",
    },
  ],
  datosFiscales: [
    {
      name: "condicionImpositiva",
      label: "Condición impositiva",
      type: "select",
      placeholder: "Seleccionar",
      minWidth: "m",
    },
    {
      name: "categoria",
      label: "Categoría",
      type: "text",
      placeholder: "",
      minWidth: "m",
    },
    {
      name: "ingresosBrutos",
      label: "Ingresos Brutos",
      type: "text",
      placeholder: "",
    },
    {
      name: "excento",
      label: "Excento",
      type: "checkbox",
    },
    {
      name: "convenioMultilateral",
      label: "Convenio Multilateral",
      type: "checkbox",
    },
    {
      name: "fechaInicio",
      label: "Fecha de inicio",
      type: "date",
      placeholder: "Seleccionar",
    },
    {
      name: "nroResHab",
      label: "Nro de Res. Hab",
      type: "number",
      placeholder: "",
    },
    {
      name: "fechaHabilitacion",
      label: "Fecha habilitación",
      type: "date",
      placeholder: "Seleccionar",
    },
    {
      name: "fechaBaja",
      label: "Fecha de baja",
      type: "date",
      placeholder: "Seleccionar",
    },
    {
      name: "vencimientoInscrip",
      label: "Vencimiento Inscrip.",
      type: "date",
      placeholder: "Seleccionar",
      disabled: true,
    },
    {
      name: "baja",
      label: "Baja",
      type: "checkbox",
    },
    {
      name: "caracterEntidad",
      label: "Caracter de la entidad",
      type: "select",
      placeholder: "Seleccionar",
      minWidth: "m",
    },
    {
      name: "otraEntidad",
      label: "Otra entidad",
      type: "text",
      placeholder: "",
      minWidth: "m",
    },
    {
      name: "situacionComercio",
      label: "Situación del comercio",
      type: "text",
      placeholder: "",
      minWidth: "m",
    },
    {
      name: "DDjj",
      label: "DDjj Anual",
      type: "checkbox",
    },
    {
      name: "vecinoDigital",
      label: "Vecino Digital",
      type: "checkbox",
    },
    {
      name: "fecha",
      label: "Fecha",
      type: "date",
      placeholder: "Año/Mes (carga automatica)",
    },
  ],
  footer: [
    {
      name: "clavePago",
      label: "Clave de pago",
      type: "text",
      placeholder: "Carga Automática",
      minWidth: "m",
      field: "clave_pago",
    },
    {
      name: "codigoGestionWeb",
      label: "Código de gestión web",
      type: "text",
      placeholder: "Carga Automática",
      minWidth: "m",
    },
  ],
}

export const domicilioComercialInputs = [
  {
    name: "calle",
    label: "Calle",
    type: "text",
    placeholder: "Ingrese la Calle",
    minWidth: "m",
  },
  {
    name: "nroDomicilio",
    label: "Nro. de domicilio",
    type: "number",
    placeholder: "Ingrese el nro.",
    minWidth: "s",
  },
  {
    name: "codigoPostal",
    label: "Código Postal",
    type: "text",
    placeholder: "Ingrese C.P",
    minWidth: "s",
  },
  {
    name: "barrio",
    label: "Barrio",
    type: "text",
    placeholder: "Ingrese el barrio",
    minWidth: "m",
  },
  {
    name: "ciudad",
    label: "Ciudad",
    type: "text",
    placeholder: "Ingrese la ciudad",
    minWidth: "m",
  },
  {
    name: "provincia",
    label: "Provincia",
    type: "text",
    placeholder: "Ingrese la provincia",
    minWidth: "m",
  },
  {
    name: "pais",
    label: "País",
    type: "text",
    placeholder: "Ingrese el país",
    minWidth: "m",
  },
]

export const fieldsState = [
  "nombrePropietario",
  "cuil",
  "fecha_cambio_domicilio",
  "ocupante",
  "cod_postal",
  "nom_calle_dom_esp",
  "nro_dom_esp",
  "manzana",
  "parcela",
  "nom_barrio_dom_esp",
  "ciudad_dom_esp",
  "superficie",
  "superficie_edificada",
  "baldio_country",
  "baldio_sucio",
  "construccion",
  "edificado",
  "exhimido",
  "jubilado",
  "parquizado",
  "union_tributaria",
  "debito_automatico",
  "saldo_adeudado",
  "ultimo_periodo",
  "emite_cedulon",
  "clave_pago",
]

export default defaultInputs
