import { VCtasctes } from "./VCtasctes";

export interface Cedulones2 {
  nro_cedulon: number;
  fecha_emision: Date | null;
  subsistema: number;
  tipo_cedulon: number;
  no_pagado: boolean;
  activo: boolean;
  nro_emision: number;
  circunscripcion: number;
  seccion: number;
  manzana: number;
  parcela: number;
  p_h: number;
  periodo: "";
  vencimiento_1: Date | null;
  monto_1: number;
  vencimiento_2: Date | null;
  monto_2: number;
  contado: number;
  cheques: number;
  monto_arreglo: number;
  nro_decreto: "";
  nro_dom_esp: number;
  piso_dpto_esp: "";
  local_esp: "";
  nom_calle_dom_esp: "";
  nom_barrio_dom_esp: "";
  ciudad_dom_esp: "";
  provincia_dom_esp: "";
  pais_dom_esp: "";
  codigo_postal_dom_esp: "";
  nro_badec: 0;
  nro_contrib: 0;
  nom_badec: "";
  nom_calle_pf: "";
  nro_dom_pf: 0;
  dominio: "";
  legajo: 0;
  imprime: 0;
  tipo_cem: "";
  manzana_cem: 0;
  lote_cem: 0;
  parcela_cem: 0;
  nivel_cem: 0;
  nro_causa: 0;
  anio: 0;
  nro_procuracion: 0;
  lstDeuda: VCtasctes[];
}
